In [103]:
import pandas as pd
import numpy as np
import json
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder
from joblib import dump, load

In [61]:
train = pd.read_csv("../data/new_train_1.csv")


In [83]:
test = pd.read_csv("../data/new_test_1.csv")

In [25]:
train.head(5)

feature_1             feature_2             feature_3           disease
0    itching             skin_rash  nodal_skin_eruptions  Fungal infection
1  skin_rash  nodal_skin_eruptions   dischromic _patches  Fungal infection
2    itching  nodal_skin_eruptions   dischromic _patches  Fungal infection
3    itching             skin_rash   dischromic _patches  Fungal infection
4    itching             skin_rash  nodal_skin_eruptions  Fungal infection

In [31]:
symptoms = json.load(open("../data/symptom.json", 'r'))
symptoms.keys()

dict_keys(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_

In [32]:
keys = list(symptoms.keys())

In [42]:
r, c = train.shape

In [62]:
for i in range(r):
    for j in range(c - 1):
        train.loc[i][j] = symptoms[train.loc[i][j]]

In [58]:
train.head(5)

feature_1 feature_2 feature_3  disease
0         0         1         2       15
1         1         2       102       15
2         0         2       102       15
3         0         1       102       15
4         0         1         2       15

In [63]:
le = LabelEncoder()

In [64]:
le.fit(train['disease'])

LabelEncoder()

In [65]:
X = train.values[:,:-1]
Y = le.transform(train['disease'])
clf = CategoricalNB()

In [ ]:
X[0]

In [ ]:
Y

In [ ]:
clf.fit(X, Y)

In [ ]:
clf.score(X, Y)

In [ ]:
r,c = test.shape
for i in range(r):
    for j in range(c - 1):
        test.loc[i][j] = symptoms[test.loc[i][j]]
        

In [ ]:
test.head(5)

In [ ]:
Xt = test.values[:,:-1]
Yt = le.transform(test['disease'])

In [ ]:
clf.score(Xt, Yt)

In [ ]:
probs = clf.predict_proba([X[0]])

In [ ]:
probs[0][15]

In [ ]:
clf.predict([[0,0,0]])

In [ ]:
np.argsort(probs)

In [ ]:
dump(clf,"../model/cnb.joblib")

In [66]:
dump(clf,"../model/cnb.joblib")

array([0, 1, 2], dtype=object)

In [67]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [68]:
clf.fit(X, Y)

CategoricalNB(alpha=1.0, class_prior=None, fit_prior=True)

In [69]:
clf.score(X, Y)

0.9402439024390243

In [85]:
r,c = test.shape
for i in range(r):
    for j in range(c - 1):
        test.loc[i][j] = symptoms[test.loc[i][j]]
        

In [86]:
test.head(5)

feature_1 feature_2 feature_3              disease
0         0         1         2     Fungal infection
1         3         4         5              Allergy
2         7         8         9                 GERD
3         0        11        32  Chronic cholestasis
4         0         1         7        Drug Reaction

In [88]:
Xt = test.values[:,:-1]
Yt = le.transform(test['disease'])

In [89]:
clf.score(Xt, Yt)

0.9512195121951219

In [99]:
probs = clf.predict_proba([X[0]])

In [108]:
probs[0][15]

0.9731879389040189

In [111]:
clf.predict([[0,0,0]])

array([8])

In [101]:
np.argsort(probs)

array([[ 0, 22, 23, 24, 25, 26, 27, 29, 21, 30, 32, 33, 34, 35, 36, 37,
        38, 31, 39, 20, 18,  1,  2,  3,  4,  5,  6,  7, 10, 40, 11, 12,
        13, 16, 17, 19, 28,  9, 14,  8, 15]], dtype=int64)

In [104]:
dump(clf,"../model/cnb.joblib")

['../model/cnb.joblib']